import Navigation from '@/components/navigation/Navigation';
import '../styles/globals.css';

export const metadata = {
	title: 'Geoservice',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head></head>
			<body>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
